# e2.py

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

fibon = {1: 1, 2: 1}

def fib(n):
    global fibon
    if n in fibon:
        return fibon[n]
    else:
        res = fib(n-1) + fib(n-2)
        fibon[n] = res
        return res

def evens(limit):
    k = 1
    l = 1
    while k <= limit:
        if not k % 2:
            yield k
        l += 1
        k = fib(l)

if __name__ == "__main__":
    print(sum(evens(4000000)))
